Add sensible default dir for system-level cert creation
chef-cookbooks/openssl pull request #44
Opened 2016-02-04 00:23 UTC by patcon

Seems that debian recommends `/etc/ssl/localcerts`. Perhaps we could create and default to this location, rather than having people scatter them around in the nginx and apache directories? Of course, this would be breaking, as it would assume the name was just a filename (without path), among other changes

Thoughts? I found myself trying to find out what the recommended cert path was in order to build defaults into a letsencrypt cookbook, and so thought it might be nice to have guidance in this cookbook)

References:
* https://wiki.debian.org/Self-Signed_Certificate
* https://www.linode.com/docs/security/ssl/how-to-make-a-selfsigned-ssl-certificate#installing-openssl

2016-02-04 00:25 UTC, patcon commented
Haven't tested yet, but curious about your thoughts on approach. thanks :)

**To Do**
- [ ] make sure default dir is created
- [ ] ensure rhel platform family dir is appropriate

2016-02-04 00:27 UTC, patcon commented
This doesn't affect resource names with absolute paths, so this should be backward compat atm

2017-12-10 18:47 UTC, tas50 commented on attributes/default.rb
> +when 'rhel'
fedora and amazon should go here as well

2018-07-23 23:09 UTC, tas50 commented on providers/x509.rb
> +                   cert_dir = new_resource.cert_dir || node['openssl']['default_x509_dir']
In general we don't want to have a resource that's dependent on a cookbook attribute. Our long term goal in this resource is to move it into chef and once we do that we won't have this attribute anymore.

2018-07-23 23:10 UTC, tas50 requested changes
The idea here is solid, but we'd need a fully contained solution within a the resource before we could merge it since we want to ship this in chef itself.

2018-08-29 16:25 UTC, tas50 commented
@patcon With Chef 14.4 we merge in a significantly reworked openssl_x509_certificate resource into the chef-client itself. At this point we're not going to be developing this cookbook further since Chef now ships with openssl resources out of the box. Thanks for putting this together and if it's still an issue with the resource in Chef 14.4 please open a PR or issue against the Chef project itself.

2018-08-29 16:25 UTC, closed without merging